# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: #manual
permissions:
  contents: write # Important: allows the action to push to the gh-pages branch
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '24.x' # Define it once here
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build -- --configuration production --base-href /${{ github.event.repository.name }}/
    - run: npm test
    - name: Deploy 🚀
      id: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist/angular-auto-mat-error/browser # The folder where Angular outputs the build
        branch: gh-pages # The branch the action will deploy to
    - name: Set URL env
      run: echo "DEPLOY_URL=${{ steps.deploy.outputs.page_url }}" >> $GITHUB_ENV
